### ISSUE TITLE
Formatter and Beatifier

### ISSUE THREAD

**Issue by Jenesius** [ivevv/OS_1#1]
Это не является таском, багом или иной сущностью влияющей на процесс сдачи лаб. работы, однако старайтесь расставлять табуляцию - это помогает лучше понимать ваш код. Рекомендую использовать *умные* редакторы как VS code или CLION от JB(я сам это использую) оно упрощает данный процесс.
![image](https://user-images.githubusercontent.com/21982550/109811411-da298180-7c3b-11eb-84f2-afa581e40c40.png)
Считаю, что код справа приятнее читать.

С Уважением, Архипцев Евгений!

**Comment by Jenesius** [comment]
@ivevv

**Comment by ivevv** [comment]
Приняла к сведению, спасибо! @Jenesius
